print("Developer: Ryan Parks")
print("Program provides file system navigation and information.\n")
print("Program Requirements:")
print("1. Write program functions that navigate and display file system information.")
print("2. Create and display program menu.")
print("Must prevent incorrect command input.\n")
print("Input:\n")
print("Current working directory:")
print("c:/tomcat/webapps/lis4930/a4/\n")
print("MENU:")
print("1. List")
print("2. Up")
print("3. Down")
print("4. Count")
print("5. Size")
print("6. Search")
print("7. Quit\n")
print("Enter command: 1\n")
print("All files and directories in c:/tomcat/webapps/lis4930/a4:")
print(".ipynb_checkpoints")
print("img")
print("a4.ipynb")
print("fileinformation.py")
print("listsanddictionaries.py")
print("my_company_data.csv")
print("README.md")
print("simpleshoppingcart.py\n")
print("")
print("Current working directory:")
print("c:/tomcat/webapps/lis4930/a4/\n")
print("MENU:")
print("1. List")
print("2. Up")
print("3. Down")
print("4. Count")
print("5. Size")
print("6. Search")
print("7. Quit\n")
print("Enter command: 2\n")
print("Current working directory:")
print("c:/tomcat/webapps/lis4930/\n")
print("MENU:")
print("1. List")
print("2. Up")
print("3. Down")
print("4. Count")
print("5. Size")
print("6. Search")
print("7. Quit\n")
print("Enter command: 3")
print("Enter directory name: a4\n")
print("Current working directory:")
print("c:/tomcat/webapps/lis4930/a4/\n")
print("MENU:")
print("1. List")
print("2. Up")
print("3. Down")
print("4. Count")
print("5. Size")
print("6. Search")
print("7. Quit\n")
print("Enter command: 4")
print("Total files: 8\n")
print("Current working directory:")
print("c:/tomcat/webapps/lis4930/a4/\n")
print("MENU:")
print("1. List")
print("2. Up")
print("3. Down")
print("4. Count")
print("5. Size")
print("6. Search")
print("7. Quit\n")
print("Enter command: 5\n")
print("Total size:")
print(" 926,720 bytes")
print(" 905 KB")
print(" .92672 MB")
print(" .0009 GB\n")
print("Current working directory:")
print("c:/tomcat/webapps/lis4930/a4/\n")
print("MENU:")
print("1. List")
print("2. Up")
print("3. Down")
print("4. Count")
print("5. Size")
print("6. Search")
print("7. Quit\n")
print("Enter command: 6")
print("Enter file name; .py\n")
print("File paths for .py:")
print("c:/tomcat/webapps/lis4930/a4/fileinformation.py")
print("c:/tomcat/webapps/lis4930/a4/listsanddictionaries.py")
print("c:/tomcat/webapps/lis4930/a4/simpleshoppingcart.py")
print("c:/tomcat/webapps/lis4930/a4/main.py")
print("c:/tomcat/webapps/lis4930/a4/functions.py\n")
print("Current working directory:")
print("c:/tomcat/webapps/lis4930/a4/\n")
print("MENU:")
print("1. List")
print("2. Up")
print("3. Down")
print("4. Count")
print("5. Size")
print("6. Search")
print("7. Quit\n")
print("Enter command: 7")
print("Stopping program.")