print("Developer: Ryan Parks")
print("Simple Shopping Cart!")
print("")
print("Program Requirements:")
print("1. Capture user-entered shopping items")
print("2. Retrieve cost for each item")
print("3. Print items, cost, and total of all items")
print("Must perform data and range validation")
print("")
print("Extra credit:")
print("a. Request tax rate: between 1% and 10%")
print("b. Print pre-tax total, total tax, and total amount with tax")
print("Must perform data and range validation")
print("")
print("Input:")
print("Enter -1 to stop program.")
print("")
print("Enter item1 name: ")
print("No item name entered! Try again.")
print("")
print("Enter item1 name: shoes")
print("Enter item2 name: shirt")
print("Enter item3 name: pants")
print("Enter item4 name: -1")
print("Stopping list.")
print("")
print("Enter shoes cost: $a")
print("Not a float! Try again.")
print("")
print("Enter shoes cost: $-1")
print("Item cost must be between $1 and $100.")
print("")
print("Enter shoes cost: $100")
print("Enter shirt cost: $90")
print("Enter pants cost: $80")
print("")
print("Item     Cost")
print("shoes    100.00")
print("shirt    90.00")
print("pants    80.00")
print("")
print("Total: $270.00")