print("Developer: Ryan Parks")
print("Guessing Game!")
print("")
print("Program Requirements:")
print("1. Create guessing game based upon pseudo-random numbers.")
print("2. Must perform data and range validation.")
print("")
print("Input:")
print("Enter lower number: a")
print("Not an int! Try again.")
print("")
print("Enter lower number: -1100")
print("Lower must be between -1000 and 1000")
print("")
print("Enter lower number: -1")
print("Enter upper number: b")
print("Not an int! Try again.")
print("")
print("Enter upper number: 1100")
print("Upper must be between -1000 and 1000")
print("")
print("Enter upper number: -2")
print("Lower number must be less than or equal to upper number! Try again.")
print("")
print("Enter lower number: -4")
print("Enter guess: -3")
print("Too low!")
print("")
print("Enter guess: -1")
print("Too high!")
print("")
print("Enter guess: -2")
print("Bingo! Number of tries: 3")
