print("Developer: Ryan Parks")
print("Pseudo-Random Number Lists!")
print("")
print("Program Requirements:")
print("1. Create pseudo-random list of numbers.")
print("2. Sort pseudo-random list of numbers.")
print("3. must perform data and range validation.")
print("")
print("Input: ")
print("Enter list size: a")
print("Not an int! Try again.")
print("")
print("Enter list size: -1")
print("List size must be between 1 and 10.")
print("")
print("Enter list size: 10")
print("")
print("Original pseudo-random number list: [3, 8, 1, 2, 5, 9, 4, 7, 10, 6]")
print("Sorted list(ascending): [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]")
print("Sorted list (descending): [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]")
