print("Developer: Ryan Parks")
print("BMI Calculator--***No Data Validation!***")
print("")
print("Program Requirements:")
print("1. Research: BMI *English System* formula.")
print("2. Must use float data type for user input and calculation.")
print("3. Format and round conversion to two decimal places.")
print("")
print("***Resources:***")
print("Accessing your weight and health risk: https://www.nhlbi.nih.gov/health/educational/lose_wt/risk.htm")
print("Body mass index tables: https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmi_tbl.htm")
print("Evaluate calculation: https://www.cdc.gov/nccdphp/dnpao/growthcharts/training/bmiage/page5_2.html")
print("")
print("Input:")
print("Enter height (inches): 70")
print("Enter weight (lbs): 170")
print("")
print("Output:")
print("height(inches) = 70.00 | weight(lbs) = 170.00 | BMI = 24.39")
