print("Developer: Ryan Parks")
print("Working with lists and user-entered values.")
print("")
print("Program requirements:")
print("1. Write a program that prints all elements of user-entered list, equal to and greater than user-entered value.")
print("2. Must perform data validation.")
print("3. Allow user to choose equal to and less than or equal to and greater than user-entered value.")
print("")
print("Input:")
print("Enter list size: a")
print("Not an integer! Try again.")
print("")
print("Enter list size: -1")
print("List length must be between 1 and 10.")
print("")
print("Enter list size: 5")
print("")
print("Add number to list: a")
print("Not an integer! Try again.")
print("")
print("Add number to list: 1")
print("Your number list: [1]")
print("")
print("Add number to list: b")
print("Not an integer! Try again.")
print("")
print("Add number to list: 2")
print("Your number list: [1, 2]")
print("")
print("Add number to list: 3")
print("Your number list: [1, 2, 3]")
print("")
print("Add number to list: 4")
print("Your number list: [1, 2, 3, 4]")
print("")
print("Add number to list: 5")
print("Your number list: [1, 2, 3, 4, 5]")
print("")
print("Add number to list: a")
print("Not an integer! Try again.")
print("")
print("Enter separating number: 3")
print("List numbers equal to and below separating number: [1, 2, 3]")